# 1. Importações

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
import numpy as np
import pandas as pd

from sklearn.metrics import make_scorer
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

# 2. Leitura dos Dados

In [5]:
path = '/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/02. Arquivos/01. Dados/03. Dados para treino e teste 100dim/'
x_train = pd.read_csv(path + 'x_train.csv', index_col=False).drop('Unnamed: 0', axis=1)
x_test = pd.read_csv(path + 'x_test.csv', index_col=False).drop('Unnamed: 0', axis=1)
y_train = pd.read_csv(path + 'y_train.csv', index_col=False).drop('Unnamed: 0', axis=1)
y_test = pd.read_csv(path + 'y_test.csv', index_col=False).drop('Unnamed: 0', axis=1)

len(x_train), len(x_test), len(y_train), len(y_test)

(1106, 277, 1106, 277)

In [6]:
x_train

0         1         2  ...        97        98        99
0     1.380696  1.117377  0.137957  ...  0.044175 -0.354515  0.294467
1     1.256561 -0.074913  0.145955  ...  0.478186  1.674268  1.021356
2     1.730329  0.072701 -0.001182  ... -0.297746  1.023306 -0.754920
3    -0.001383 -0.068355 -0.176925  ... -0.570670  0.556745  0.301391
4     0.708433 -1.674911 -0.414836  ...  0.472911  1.846100 -0.547965
...        ...       ...       ...  ...       ...       ...       ...
1101  1.558470 -1.402460 -0.173413  ...  0.170273  0.874478  1.436968
1102  1.352577 -0.150057  0.989147  ... -0.938817  0.635980  1.474042
1103  0.670228 -0.988106 -0.413070  ...  0.094762  1.008392  0.635066
1104  0.981398 -0.395133  0.129016  ...  0.048547 -1.280537 -0.083251
1105  1.362916 -1.511002  0.666810  ... -0.345845  0.053378  1.054750

[1106 rows x 100 columns]

# 3. Regressão Logística

In [7]:
class LosgisticRegression():
    def __init__(self, alpha=0.001, epochs=100):
        self.alpha = alpha 
        self.epochs = epochs
        self.errors = []
        

    def sigmoide(self, x, w):
        return 1/(1+np.exp(-x @ w))

    def loss_cross_entropy(self, sum_error):
        return (1/(2*self.N))*sum_error

    # def gradient_descendent(self):
    #     return True
    
    # def stocatic_gradiend_descendent(self):
    #     return True

    def fit(self, x_train, y_train):
        self.D = x_train.shape[1]
        self.N = x_train.shape[0]
        self.w = np.zeros(self.D + 1)
        x_train = np.hstack((np.ones((self.N, 1)), x_train))

        for epoch in range(self.epochs):
            sum_error, sum_ = 0, 0
            for i in range(self.N):
                current_error = y_train[i] - self.sigmoide(x_train[i], self.w)
                sum_error += current_error**2
                sum_ += current_error * np.transpose(x_train[i])
            self.w = np.transpose(self.w) + (self.alpha * (1/self.N) * sum_)
            self.errors.append(self.loss_cross_entropy(sum_error))

    def predict(self, x_test):
        x_test = np.hstack((np.ones((x_test.shape[0], 1)), x_test))
        return [1 if self.sigmoide(row, self.w) >= 0.5 else 0 for row in x_test]
        

## Treino

In [8]:
num_epochs = 250
alphas = [0.01, 0.001, 0.0001, 0.00001, 5, 3, 10]

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_validation, Y_train, Y_validation = train_test_split(x_train, y_train["classification"], test_size=0.2, random_state=42)
len(X_train), len(X_validation), len(Y_train), len(Y_validation)

(884, 222, 884, 222)

In [10]:
print("------ GRID SEARCH ---------")
accs = []
for alpha in alphas:
    lg = LosgisticRegression(alpha, num_epochs)
    lg.fit(X_train, Y_train.values)
    y_predict = lg.predict(X_validation)
    print(" ------------ ALPHA = " + str(alpha) + " --------------------")
    print('Test Accuraccy: ', accuracy_score(Y_validation, y_predict))
    print('\nConfusion Matrix:')
    print(confusion_matrix(Y_validation, y_predict))
    print(classification_report(Y_validation, y_predict, output_dict=True))
    accs.append((alpha, accuracy_score(Y_validation, y_predict)))
    report = classification_report(Y_validation, y_predict, output_dict=True)



------ GRID SEARCH ---------
 ------------ ALPHA = 0.01 --------------------
Test Accuraccy:  0.7702702702702703

Confusion Matrix:
[[100  11]
 [ 40  71]]
{'0': {'precision': 0.7142857142857143, 'recall': 0.9009009009009009, 'f1-score': 0.796812749003984, 'support': 111}, '1': {'precision': 0.8658536585365854, 'recall': 0.6396396396396397, 'f1-score': 0.7357512953367876, 'support': 111}, 'accuracy': 0.7702702702702703, 'macro avg': {'precision': 0.7900696864111498, 'recall': 0.7702702702702703, 'f1-score': 0.7662820221703859, 'support': 222}, 'weighted avg': {'precision': 0.7900696864111498, 'recall': 0.7702702702702703, 'f1-score': 0.7662820221703859, 'support': 222}}
 ------------ ALPHA = 0.001 --------------------
Test Accuraccy:  0.5990990990990991

Confusion Matrix:
[[109   2]
 [ 87  24]]
{'0': {'precision': 0.5561224489795918, 'recall': 0.9819819819819819, 'f1-score': 0.7100977198697068, 'support': 111}, '1': {'precision': 0.9230769230769231, 'recall': 0.21621621621621623, 'f1-sc

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


 ------------ ALPHA = 10 --------------------
Test Accuraccy:  0.7927927927927928

Confusion Matrix:
[[96 15]
 [31 80]]
{'0': {'precision': 0.7559055118110236, 'recall': 0.8648648648648649, 'f1-score': 0.8067226890756303, 'support': 111}, '1': {'precision': 0.8421052631578947, 'recall': 0.7207207207207207, 'f1-score': 0.7766990291262136, 'support': 111}, 'accuracy': 0.7927927927927928, 'macro avg': {'precision': 0.7990053874844592, 'recall': 0.7927927927927928, 'f1-score': 0.7917108591009219, 'support': 222}, 'weighted avg': {'precision': 0.7990053874844593, 'recall': 0.7927927927927928, 'f1-score': 0.791710859100922, 'support': 222}}


In [11]:
lista_ = [acc for alpha, acc in accs]
best_alpha = accs[lista_.index(max(lista_))][0]
best_alpha

10

In [12]:
lg = LosgisticRegression(best_alpha, num_epochs)
lg.fit(x_train, y_train['classification'].values)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:9: RuntimeWarning: overflow encountered in exp
  if __name__ == '__main__':


## Predição

In [13]:
y_predict = lg.predict(x_test)

## Métricas

In [14]:
print('Test Accuraccy: ', accuracy_score(y_test, y_predict))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_predict))
report = classification_report(y_test, y_predict, output_dict=True)

Test Accuraccy:  0.7256317689530686

Confusion Matrix:
[[126   4]
 [ 72  75]]


In [15]:
report

{'0': {'f1-score': 0.7682926829268293,
  'precision': 0.6363636363636364,
  'recall': 0.9692307692307692,
  'support': 130},
 '1': {'f1-score': 0.663716814159292,
  'precision': 0.9493670886075949,
  'recall': 0.5102040816326531,
  'support': 147},
 'accuracy': 0.7256317689530686,
 'macro avg': {'f1-score': 0.7160047485430606,
  'precision': 0.7928653624856157,
  'recall': 0.7397174254317112,
  'support': 277},
 'weighted avg': {'f1-score': 0.7127957417397246,
  'precision': 0.8024701615616937,
  'recall': 0.7256317689530686,
  'support': 277}}

## Salvando resultados

In [16]:
resultados = pd.DataFrame({
    'precision': report['weighted avg']['precision'], 
    'recall': report['weighted avg']['recall'], 
    'f1score': report['weighted avg']['f1-score'], 
    'y_predict': [y_predict],
    'y_real': [y_test['classification'].values],
    'hiperparams': str({'alpha': best_alpha})
})
resultados.to_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/1. Regressão Logística/regressao_logistica_100dim.json')

In [17]:
pd.read_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/1. Regressão Logística/regressao_logistica_100dim.json')

precision  ...    hiperparams
0    0.80247  ...  {'alpha': 10}

[1 rows x 6 columns]

# 4. Análise Discriminante Gaussiano

In [18]:
import numpy as np
from scipy.stats import multivariate_normal

class GaussianDiscriminant():
  def __init__(self):
    pass

  def fitAGD(self, X, y):
    self.__classes = np.unique(y) # pegando as classes e ocorrencias
    numClasses = len(self.__classes) #numero de classes
    n, numFeatures = X.shape # numero de linhas e colunas do dataset 
    
    self.__sigma = 0
    self.__probabilidadeClasses = np.zeros((numClasses, 1))
    self.__media = np.zeros((numClasses, numFeatures)) # criando a lista da media das classes por feature

    for i in range(numClasses):
        # flatnonzero retorna os indices em que os valores são diferentes de zero. O retorno é uma lista flat. 
        # A comparação y == classes vai retornar um array de 0's e 1's. 
        # E portanto a operaçao final vai pegar todos os indices em que a classe é igual ao y.
        indices = np.flatnonzero(y == self.__classes[i])

        self.__probabilidadeClasses[i] = len(indices)/ n
        self.__media[i] = np.mean(X[indices], axis=0)
        self.__sigma += np.cov(X[indices].T) *(len(indices)-1)
        
    self.__sigma /= n
    
    return {'media': self.__media, 'covar': self.__sigma, 'classes': self.__classes, 'numRows': n, 'numClasses': numClasses, 
            'numFeatures': numFeatures, 'probabilidadeClasses': self.__probabilidadeClasses }

  def predict(self,X):
    # Usando a distribuição gaussiana multivariada da biblioteca scipy.stats
    # Basicamente o calculo da função densidade de probabilidade visto na imagem abaixo.
    pdf = lambda mean: multivariate_normal.pdf(X, mean=mean, cov=self.__sigma)

    # Apply a function to 1-D slices along the given axis
    # No caso aplica a função fdp no axis 1 das médias
    y_probs = np.apply_along_axis(pdf, 1, self.__media) * self.__probabilidadeClasses

    return self.__classes[np.argmax(y_probs, axis=0)]


## Treino

In [19]:
agd = GaussianDiscriminant()
fit = agd.fitAGD(x_train.to_numpy(), y_train)


## Predição

In [20]:
y_predict = agd.predict(x_test.to_numpy())

## Métricas

In [21]:
print('Test Accuraccy: ', accuracy_score(y_test, y_predict))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_predict))
report = classification_report(y_test, y_predict, output_dict=True)

Test Accuraccy:  0.8158844765342961

Confusion Matrix:
[[105  25]
 [ 26 121]]


In [22]:
report

{'0': {'f1-score': 0.8045977011494252,
  'precision': 0.8015267175572519,
  'recall': 0.8076923076923077,
  'support': 130},
 '1': {'f1-score': 0.825938566552901,
  'precision': 0.8287671232876712,
  'recall': 0.8231292517006803,
  'support': 147},
 'accuracy': 0.8158844765342961,
 'macro avg': {'f1-score': 0.8152681338511631,
  'precision': 0.8151469204224615,
  'recall': 0.815410779696494,
  'support': 277},
 'weighted avg': {'f1-score': 0.8159229979519917,
  'precision': 0.8159828173492073,
  'recall': 0.8158844765342961,
  'support': 277}}

## Salvando resultados

In [23]:
resultados = pd.DataFrame({
    'precision': report['weighted avg']['precision'], 
    'recall': report['weighted avg']['recall'], 
    'f1score': report['weighted avg']['f1-score'], 
    'y_predict': [y_predict],
    'y_real': [y_test['classification'].values],
})
resultados.to_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/3. Análise Discriminante Gaussiano/agd_100dim.json')

In [24]:
resultados

precision  ...                                             y_real
0   0.815983  ...  [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, ...

[1 rows x 5 columns]

In [25]:
pd.read_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/3. Análise Discriminante Gaussiano/agd_100dim.json')

precision  ...                                             y_real
0   0.815983  ...  [1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, ...

[1 rows x 5 columns]

# 5. Árvore de Decisão

## Treino

In [26]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeClassifier

max_depths = [1, 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60]
params = {'criterion': ['gini','entropy'], 'max_depth': max_depths}

clf = GridSearchCV(DecisionTreeClassifier(), params, verbose=2)
    
print("[Árvore de Decisão] Treinando modelos...")
clf.fit(x_train, y_train['classification'].values)

[Árvore de Decisão] Treinando modelos...
Fitting 5 folds for each of 26 candidates, totalling 130 fits
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=5 ............

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 130 out of 130 | elapsed:   11.2s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                

In [27]:
params = clf.best_params_
print("Parâmetros escolhidos para Árvore de Decisão: ", clf.best_params_)

Parâmetros escolhidos para Árvore de Decisão:  {'criterion': 'gini', 'max_depth': 50}


## Predição

In [28]:
y_predict = clf.predict(x_test)

## Métricas

In [29]:
print('Test Accuraccy: ', accuracy_score(y_test, y_predict))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_predict))
report = classification_report(y_test, y_predict, output_dict=True)
report

Test Accuraccy:  0.7184115523465704

Confusion Matrix:
[[ 90  40]
 [ 38 109]]


{'0': {'f1-score': 0.6976744186046512,
  'precision': 0.703125,
  'recall': 0.6923076923076923,
  'support': 130},
 '1': {'f1-score': 0.7364864864864866,
  'precision': 0.7315436241610739,
  'recall': 0.7414965986394558,
  'support': 147},
 'accuracy': 0.7184115523465704,
 'macro avg': {'f1-score': 0.717080452545569,
  'precision': 0.7173343120805369,
  'recall': 0.716902145473574,
  'support': 277},
 'weighted avg': {'f1-score': 0.7182714365780439,
  'precision': 0.7182063637244688,
  'recall': 0.7184115523465704,
  'support': 277}}

## Salvando resultados

In [30]:
resultados = pd.DataFrame({
    'precision': report['weighted avg']['precision'], 
    'recall': report['weighted avg']['recall'], 
    'f1score': report['weighted avg']['f1-score'], 
    'y_predict': [y_predict],
    'y_real': [y_test['classification'].values],
    'hiperparams': str(clf.best_params_)
})
resultados.to_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/5. Árvore de Decisão/ad_100dim.json')

In [31]:
pd.read_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/5. Árvore de Decisão/ad_100dim.json')

precision  ...                             hiperparams
0   0.718206  ...  {'criterion': 'gini', 'max_depth': 50}

[1 rows x 6 columns]

# 6. Random Forest

## Treino

In [32]:
from sklearn.ensemble import RandomForestClassifier

print("[RANDOM FOREST] Selecionando hiperparâmetros...")
num_estimators = [100, 110, 120, 130, 140, 150]
max_depths = [1, 5, 10, 15, 20, 25, 55, 60]

params = {'criterion': ['gini','entropy'],
          'n_estimators': num_estimators,
          'max_depth': max_depths
          }

# params
clt = GridSearchCV(RandomForestClassifier(), params, verbose=2)

print("[RANDOM FOREST] Treinando modelo...")
clf.fit(x_train, y_train['classification'])

[RANDOM FOREST] Selecionando hiperparâmetros...
[RANDOM FOREST] Treinando modelo...
Fitting 5 folds for each of 26 candidates, totalling 130 fits
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=1 .....................................
[CV] ...................... criterion=gini, max_depth=1, total=   0.0s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[C

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] ...................... criterion=gini, max_depth=5, total=   0.1s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=5 .....................................
[CV] ...................... criterion=gini, max_depth=5, total=   0.0s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] ..................... criterion=gini, max_depth=10, total=   0.1s
[CV] criterion=gini, max_depth=10 ....................................
[CV] .

[Parallel(n_jobs=1)]: Done 130 out of 130 | elapsed:   11.2s finished


GridSearchCV(cv=None, error_score=nan,
             estimator=DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort='deprecated',
                                              random_state=None,
                                              splitter='best'),
             iid='deprecated', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                

In [33]:
print("[RANDOM FOREST] Hiperparâmetros escolhidos para Radom Forest: ", clf.best_params_)

[RANDOM FOREST] Hiperparâmetros escolhidos para Radom Forest:  {'criterion': 'gini', 'max_depth': 45}


## Predição

In [34]:
y_predict = clf.predict(x_test)

## Métricas

In [35]:
print('Test Accuraccy: ', accuracy_score(y_test, y_predict))
print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_predict))
report = classification_report(y_test, y_predict, output_dict=True)
report

Test Accuraccy:  0.6787003610108303

Confusion Matrix:
[[ 87  43]
 [ 46 101]]


{'0': {'f1-score': 0.6615969581749049,
  'precision': 0.6541353383458647,
  'recall': 0.6692307692307692,
  'support': 130},
 '1': {'f1-score': 0.6941580756013744,
  'precision': 0.7013888888888888,
  'recall': 0.6870748299319728,
  'support': 147},
 'accuracy': 0.6787003610108303,
 'macro avg': {'f1-score': 0.6778775168881397,
  'precision': 0.6777621136173768,
  'recall': 0.678152799581371,
  'support': 277},
 'weighted avg': {'f1-score': 0.6788766847514068,
  'precision': 0.6792121323163504,
  'recall': 0.6787003610108303,
  'support': 277}}

## Salvando métricas

In [36]:
resultados = pd.DataFrame({
    'precision': report['weighted avg']['precision'], 
    'recall': report['weighted avg']['recall'], 
    'f1score': report['weighted avg']['f1-score'], 
    'y_predict': [y_predict],
    'y_real': [y_test['classification'].values],
    'hiperparams': str(clf.best_params_)
})
resultados.to_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/8. Random Forest/random_forest_100dim.json')

In [37]:
pd.read_json('/content/drive/My Drive/[2020.1] APRENDIZADO DE MÁQUINA/TRABALHO/05. Resultados/5.1. Resultados dos modelos/8. Random Forest/random_forest_100dim.json')

precision  ...                             hiperparams
0   0.679212  ...  {'criterion': 'gini', 'max_depth': 45}

[1 rows x 6 columns]